In [4]:
import numpy as np

# In-Class Exercise 1 #
a = np.ones((3, 3))
b = np.concatenate((a, 2*a, 3*a), axis=1)
b

array([[1., 1., 1., 2., 2., 2., 3., 3., 3.],
       [1., 1., 1., 2., 2., 2., 3., 3., 3.],
       [1., 1., 1., 2., 2., 2., 3., 3., 3.]])

In [5]:
# In-Class Exercise 2 #
def generate(n):
    a = np.ones((n, n))
    b = np.identity(n)
    result = a - b
    return result

generate(3)

array([[0., 1., 1.],
       [1., 0., 1.],
       [1., 1., 0.]])

In [15]:
import numpy as np

# Generate an nxn matrix containing all the integers
# contained in [1, n*n] sorted by row/column. (Don't use loops!)

# Precondition: n > 0

def sorted_n_squared_matrix(n):
    # Step 1: Make an array of size nxn. e.g., [1, 2, ..., n] #
    # Step 2: Resize the array into an nxn matrix.            #
    # Step 3: Feel pride from your 1-line solution :)         #
    return np.arange(1, n*n + 1, 1).reshape(n, n)

sorted_n_squared_matrix(10)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])